server:
  port: 8283

spring:
  application:
    name: user-service-jwt

  devtools:
    add-properties: true

  datasource:
    url: jdbc:mysql://localhost:3306/app_user_data
    username:
    password: 

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format-sql: true

